import Head from "next/head";
import { Grid } from "../components/Grid";
import styles from "../styles/Home.module.css";
import { data } from "../data";
export const getStaticProps = async () => {
  return {
    props: {
      dataList: data,
    },
  };
};
export default function Home({ dataList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Grid dataList={dataList}></Grid>
    </div>
  );
}
